/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.store.pos.gui;

import com.store.pos.model.entity.SupplierDetails;
import com.store.pos.model.entity.User;
import com.store.pos.model.entity.controller.SupplierDetailsJpaController;
import com.store.pos.model.entity.controller.UserJpaController;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import javax.swing.JFrame;

/**
 *
 * @author Sanjeewa;
 */
public class MainMenu extends javax.swing.JFrame {
    
    EntityManagerFactory emfactory = Persistence.createEntityManagerFactory("POSsystemPU");
    EntityManager entitymanager = emfactory.createEntityManager();

    /**
     * Creates new form MainMenu
     */
    public MainMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane7 = new javax.swing.JTabbedPane();
        tabControl = new javax.swing.JPanel();
        controlLeftPanel = new javax.swing.JPanel();
        btn_UserAcc = new javax.swing.JButton();
        btn_userControl = new javax.swing.JButton();
        btn_Profit = new javax.swing.JButton();
        btn_customerReg = new javax.swing.JButton();
        btn_supplierReg = new javax.swing.JButton();
        btn_customerLoan = new javax.swing.JButton();
        controlPanel = new javax.swing.JPanel();
        panel_UserAcc = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        tf_userAcc_Name = new javax.swing.JTextField();
        tf_userAcc_SecurityA = new javax.swing.JTextField();
        tf_userAcc_Password = new javax.swing.JPasswordField();
        tf_userAcc_confirmPass = new javax.swing.JPasswordField();
        rb_userAcc_Admin = new javax.swing.JRadioButton();
        rb_userAcc_user = new javax.swing.JRadioButton();
        btn_userAcc_save = new javax.swing.JButton();
        btn_userAcc_newUser = new javax.swing.JButton();
        cb_userAcc_SecurityQ = new javax.swing.JComboBox();
        panel_userControl = new javax.swing.JPanel();
        panel_Profit = new javax.swing.JPanel();
        panel_customerReg = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        tf_customReg_name = new javax.swing.JTextField();
        tf_customReg_Tel = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        tf_customReg_loan = new javax.swing.JTextField();
        tf_customReg_loanPeriod = new javax.swing.JTextField();
        rb_customReg_active = new javax.swing.JRadioButton();
        rb_customReg_deactive = new javax.swing.JRadioButton();
        jLabel25 = new javax.swing.JLabel();
        tf_customReg_Address1 = new javax.swing.JTextField();
        tf_customReg_Address2 = new javax.swing.JTextField();
        tf_customReg_Address3 = new javax.swing.JTextField();
        btn_customReg_save = new javax.swing.JButton();
        btn_customReg_newCustomer = new javax.swing.JButton();
        panel_supplierReg = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        tf_supReg_contactName = new javax.swing.JTextField();
        tf_supReg_supName = new javax.swing.JTextField();
        tf_supReg_address1 = new javax.swing.JTextField();
        tf_supReg_address2 = new javax.swing.JTextField();
        tf_supReg_address3 = new javax.swing.JTextField();
        tf_supReg_telNo = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        cb_supReg_category = new javax.swing.JComboBox();
        tf_supReg_faxNo = new javax.swing.JTextField();
        tf_supReg_loan = new javax.swing.JTextField();
        tf_supReg_loanPeriod = new javax.swing.JTextField();
        btn_supReg_newCustomer = new javax.swing.JButton();
        btn_supReg_save = new javax.swing.JButton();
        panel_customerLoan = new javax.swing.JPanel();
        tabItem = new javax.swing.JPanel();
        tabTransaction = new javax.swing.JPanel();
        tabReport = new javax.swing.JPanel();
        tabAction = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(885, 500));

        jTabbedPane7.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N

        tabControl.setLayout(new java.awt.BorderLayout());

        controlLeftPanel.setBackground(new java.awt.Color(204, 204, 255));
        controlLeftPanel.setPreferredSize(new java.awt.Dimension(140, 526));

        btn_UserAcc.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btn_UserAcc.setText("User");
        btn_UserAcc.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_UserAcc.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_UserAcc.setPreferredSize(new java.awt.Dimension(73, 60));
        btn_UserAcc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_UserAccActionPerformed(evt);
            }
        });

        btn_userControl.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btn_userControl.setText("User Control");
        btn_userControl.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_userControl.setPreferredSize(new java.awt.Dimension(73, 60));
        btn_userControl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_userControlActionPerformed(evt);
            }
        });

        btn_Profit.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btn_Profit.setText("Profit");
        btn_Profit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_Profit.setPreferredSize(new java.awt.Dimension(73, 60));
        btn_Profit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ProfitActionPerformed(evt);
            }
        });

        btn_customerReg.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btn_customerReg.setText("Customer Reg");
        btn_customerReg.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_customerReg.setPreferredSize(new java.awt.Dimension(73, 60));
        btn_customerReg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_customerRegActionPerformed(evt);
            }
        });

        btn_supplierReg.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btn_supplierReg.setText("Supplier Reg");
        btn_supplierReg.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_supplierReg.setPreferredSize(new java.awt.Dimension(73, 60));
        btn_supplierReg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_supplierRegActionPerformed(evt);
            }
        });

        btn_customerLoan.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btn_customerLoan.setText("Customer Loan");
        btn_customerLoan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_customerLoan.setPreferredSize(new java.awt.Dimension(73, 60));
        btn_customerLoan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_customerLoanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout controlLeftPanelLayout = new javax.swing.GroupLayout(controlLeftPanel);
        controlLeftPanel.setLayout(controlLeftPanelLayout);
        controlLeftPanelLayout.setHorizontalGroup(
            controlLeftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(controlLeftPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(controlLeftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_UserAcc, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                    .addComponent(btn_userControl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_Profit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_customerReg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_supplierReg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_customerLoan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        controlLeftPanelLayout.setVerticalGroup(
            controlLeftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(controlLeftPanelLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(btn_UserAcc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_userControl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_Profit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_customerReg, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_supplierReg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_customerLoan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(137, Short.MAX_VALUE))
        );

        tabControl.add(controlLeftPanel, java.awt.BorderLayout.LINE_START);

        controlPanel.setBackground(new java.awt.Color(236, 227, 200));
        controlPanel.setLayout(new java.awt.CardLayout());

        panel_UserAcc.setBackground(new java.awt.Color(221, 206, 215));
        panel_UserAcc.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "User Accounts", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 0, 14))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel1.setText("Name");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel2.setText("Password");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel3.setText("Confirm Password");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel4.setText("Security Question");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel5.setText("Security Answer");

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel6.setText("User Type");

        rb_userAcc_Admin.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        rb_userAcc_Admin.setText("Admin");

        rb_userAcc_user.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        rb_userAcc_user.setText("User");
        rb_userAcc_user.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb_userAcc_userActionPerformed(evt);
            }
        });

        btn_userAcc_save.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btn_userAcc_save.setText("Save");
        btn_userAcc_save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_userAcc_saveActionPerformed(evt);
            }
        });

        btn_userAcc_newUser.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btn_userAcc_newUser.setText("Create New");

        cb_userAcc_SecurityQ.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout panel_UserAccLayout = new javax.swing.GroupLayout(panel_UserAcc);
        panel_UserAcc.setLayout(panel_UserAccLayout);
        panel_UserAccLayout.setHorizontalGroup(
            panel_UserAccLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_UserAccLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(panel_UserAccLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addGroup(panel_UserAccLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tf_userAcc_Name, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panel_UserAccLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(tf_userAcc_confirmPass, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                        .addComponent(tf_userAcc_Password)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 177, Short.MAX_VALUE)
                .addGroup(panel_UserAccLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_UserAccLayout.createSequentialGroup()
                        .addComponent(btn_userAcc_save, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(btn_userAcc_newUser, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panel_UserAccLayout.createSequentialGroup()
                        .addGroup(panel_UserAccLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(panel_UserAccLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(panel_UserAccLayout.createSequentialGroup()
                                .addComponent(rb_userAcc_Admin, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(43, 43, 43)
                                .addComponent(rb_userAcc_user, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(tf_userAcc_SecurityA, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                            .addComponent(cb_userAcc_SecurityQ, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(88, 88, 88))
        );
        panel_UserAccLayout.setVerticalGroup(
            panel_UserAccLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_UserAccLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(panel_UserAccLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                    .addGroup(panel_UserAccLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tf_userAcc_Name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cb_userAcc_SecurityQ, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(27, 27, 27)
                .addGroup(panel_UserAccLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_userAcc_Password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_userAcc_SecurityA, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(panel_UserAccLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rb_userAcc_user)
                    .addComponent(rb_userAcc_Admin)
                    .addComponent(tf_userAcc_confirmPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(60, 60, 60)
                .addGroup(panel_UserAccLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_userAcc_newUser, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_userAcc_save, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(238, Short.MAX_VALUE))
        );

        controlPanel.add(panel_UserAcc, "card7");

        panel_userControl.setBackground(new java.awt.Color(233, 222, 217));

        javax.swing.GroupLayout panel_userControlLayout = new javax.swing.GroupLayout(panel_userControl);
        panel_userControl.setLayout(panel_userControlLayout);
        panel_userControlLayout.setHorizontalGroup(
            panel_userControlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1125, Short.MAX_VALUE)
        );
        panel_userControlLayout.setVerticalGroup(
            panel_userControlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 548, Short.MAX_VALUE)
        );

        controlPanel.add(panel_userControl, "card6");

        panel_Profit.setBackground(new java.awt.Color(208, 227, 217));

        javax.swing.GroupLayout panel_ProfitLayout = new javax.swing.GroupLayout(panel_Profit);
        panel_Profit.setLayout(panel_ProfitLayout);
        panel_ProfitLayout.setHorizontalGroup(
            panel_ProfitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1125, Short.MAX_VALUE)
        );
        panel_ProfitLayout.setVerticalGroup(
            panel_ProfitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 548, Short.MAX_VALUE)
        );

        controlPanel.add(panel_Profit, "card5");

        panel_customerReg.setBackground(new java.awt.Color(227, 213, 185));
        panel_customerReg.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "CustomerRegistration", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 0, 14))); // NOI18N

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel7.setText("Customer Name");

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel8.setText("Address  :");

        jLabel9.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel9.setText("Field 2");

        jLabel10.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel10.setText("Field 3");

        jLabel11.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel11.setText("Telephone No");

        jLabel22.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel22.setText("Loan");

        jLabel23.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel23.setText("Loan Period");

        jLabel24.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel24.setText("Customer Type");

        rb_customReg_active.setText("Active");

        rb_customReg_deactive.setText("Deactive");

        jLabel25.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel25.setText("Field 1");

        btn_customReg_save.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btn_customReg_save.setText("Save");

        btn_customReg_newCustomer.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btn_customReg_newCustomer.setText("New Customer");

        javax.swing.GroupLayout panel_customerRegLayout = new javax.swing.GroupLayout(panel_customerReg);
        panel_customerReg.setLayout(panel_customerRegLayout);
        panel_customerRegLayout.setHorizontalGroup(
            panel_customerRegLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_customerRegLayout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(panel_customerRegLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panel_customerRegLayout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panel_customerRegLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel25, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panel_customerRegLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tf_customReg_Tel, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_customReg_name, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_customReg_Address1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_customReg_Address2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_customReg_Address3, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(314, 314, 314)
                .addGroup(panel_customerRegLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panel_customerRegLayout.createSequentialGroup()
                        .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tf_customReg_loan, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panel_customerRegLayout.createSequentialGroup()
                        .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tf_customReg_loanPeriod, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panel_customerRegLayout.createSequentialGroup()
                        .addGroup(panel_customerRegLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_customReg_save, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(panel_customerRegLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panel_customerRegLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(rb_customReg_active)
                                .addGap(18, 18, 18)
                                .addComponent(rb_customReg_deactive))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_customerRegLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btn_customReg_newCustomer)))))
                .addContainerGap(71, Short.MAX_VALUE))
        );
        panel_customerRegLayout.setVerticalGroup(
            panel_customerRegLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_customerRegLayout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(panel_customerRegLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_customerRegLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(tf_customReg_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panel_customerRegLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(tf_customReg_loan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(panel_customerRegLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_customReg_loanPeriod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_customReg_Address1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panel_customerRegLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_customerRegLayout.createSequentialGroup()
                        .addGroup(panel_customerRegLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_customerRegLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(tf_customReg_Address2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(panel_customerRegLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tf_customReg_Address3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25)
                        .addGroup(panel_customerRegLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tf_customReg_Tel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_customReg_save, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_customReg_newCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panel_customerRegLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(rb_customReg_active)
                        .addComponent(rb_customReg_deactive)))
                .addContainerGap(238, Short.MAX_VALUE))
        );

        controlPanel.add(panel_customerReg, "card4");

        panel_supplierReg.setBackground(new java.awt.Color(209, 207, 203));
        panel_supplierReg.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Supplier Registration", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 0, 14))); // NOI18N

        jLabel12.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel12.setText("Supplier Name");

        jLabel13.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel13.setText("Contact Person Name");

        jLabel14.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel14.setText("Address Field 1");

        jLabel15.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel15.setText("Address Field 2");

        jLabel16.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel16.setText("Address Field 3");

        jLabel17.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel17.setText("Telephone No");

        jLabel18.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel18.setText("Loan");

        jLabel19.setText("Fax No");

        jLabel20.setText("Loan Period");

        jLabel21.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel21.setText("Category");

        cb_supReg_category.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btn_supReg_newCustomer.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btn_supReg_newCustomer.setText("New Customer");
        btn_supReg_newCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_supReg_newCustomerActionPerformed(evt);
            }
        });

        btn_supReg_save.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btn_supReg_save.setText("Save");
        btn_supReg_save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_supReg_saveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_supplierRegLayout = new javax.swing.GroupLayout(panel_supplierReg);
        panel_supplierReg.setLayout(panel_supplierRegLayout);
        panel_supplierRegLayout.setHorizontalGroup(
            panel_supplierRegLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_supplierRegLayout.createSequentialGroup()
                .addGroup(panel_supplierRegLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_supplierRegLayout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(panel_supplierRegLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(panel_supplierRegLayout.createSequentialGroup()
                                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tf_supReg_address3))
                            .addGroup(panel_supplierRegLayout.createSequentialGroup()
                                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tf_supReg_address2))
                            .addGroup(panel_supplierRegLayout.createSequentialGroup()
                                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tf_supReg_address1))
                            .addGroup(panel_supplierRegLayout.createSequentialGroup()
                                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tf_supReg_contactName, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panel_supplierRegLayout.createSequentialGroup()
                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tf_supReg_supName)))
                        .addGap(250, 250, 250)
                        .addGroup(panel_supplierRegLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
                            .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(panel_supplierRegLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cb_supReg_category, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tf_supReg_telNo, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tf_supReg_faxNo, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tf_supReg_loan, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tf_supReg_loanPeriod, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panel_supplierRegLayout.createSequentialGroup()
                        .addGap(290, 290, 290)
                        .addComponent(btn_supReg_save, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(85, 85, 85)
                        .addComponent(btn_supReg_newCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(244, Short.MAX_VALUE))
        );
        panel_supplierRegLayout.setVerticalGroup(
            panel_supplierRegLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_supplierRegLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(panel_supplierRegLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_supReg_supName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_supReg_telNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panel_supplierRegLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_supReg_contactName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_supReg_faxNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panel_supplierRegLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_supReg_address1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_supReg_loan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panel_supplierRegLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_supReg_address2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_supReg_loanPeriod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panel_supplierRegLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_supReg_address3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cb_supReg_category, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(panel_supplierRegLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_supReg_newCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_supReg_save, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(227, Short.MAX_VALUE))
        );

        controlPanel.add(panel_supplierReg, "card3");

        panel_customerLoan.setBackground(new java.awt.Color(198, 213, 193));
        panel_customerLoan.setPreferredSize(new java.awt.Dimension(661, 500));

        javax.swing.GroupLayout panel_customerLoanLayout = new javax.swing.GroupLayout(panel_customerLoan);
        panel_customerLoan.setLayout(panel_customerLoanLayout);
        panel_customerLoanLayout.setHorizontalGroup(
            panel_customerLoanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1125, Short.MAX_VALUE)
        );
        panel_customerLoanLayout.setVerticalGroup(
            panel_customerLoanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 548, Short.MAX_VALUE)
        );

        controlPanel.add(panel_customerLoan, "card2");

        tabControl.add(controlPanel, java.awt.BorderLayout.CENTER);

        jTabbedPane7.addTab("     Control     ", tabControl);

        javax.swing.GroupLayout tabItemLayout = new javax.swing.GroupLayout(tabItem);
        tabItem.setLayout(tabItemLayout);
        tabItemLayout.setHorizontalGroup(
            tabItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1265, Short.MAX_VALUE)
        );
        tabItemLayout.setVerticalGroup(
            tabItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 548, Short.MAX_VALUE)
        );

        jTabbedPane7.addTab("       Item       ", tabItem);

        javax.swing.GroupLayout tabTransactionLayout = new javax.swing.GroupLayout(tabTransaction);
        tabTransaction.setLayout(tabTransactionLayout);
        tabTransactionLayout.setHorizontalGroup(
            tabTransactionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1265, Short.MAX_VALUE)
        );
        tabTransactionLayout.setVerticalGroup(
            tabTransactionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 548, Short.MAX_VALUE)
        );

        jTabbedPane7.addTab("    Transaction    ", tabTransaction);

        javax.swing.GroupLayout tabReportLayout = new javax.swing.GroupLayout(tabReport);
        tabReport.setLayout(tabReportLayout);
        tabReportLayout.setHorizontalGroup(
            tabReportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1265, Short.MAX_VALUE)
        );
        tabReportLayout.setVerticalGroup(
            tabReportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 548, Short.MAX_VALUE)
        );

        jTabbedPane7.addTab("      Report      ", tabReport);

        javax.swing.GroupLayout tabActionLayout = new javax.swing.GroupLayout(tabAction);
        tabAction.setLayout(tabActionLayout);
        tabActionLayout.setHorizontalGroup(
            tabActionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1265, Short.MAX_VALUE)
        );
        tabActionLayout.setVerticalGroup(
            tabActionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 548, Short.MAX_VALUE)
        );

        jTabbedPane7.addTab("      Action      ", tabAction);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane7)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane7)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_UserAccActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_UserAccActionPerformed
        controlPanel.removeAll();
        controlPanel.add(panel_UserAcc);
        controlPanel.repaint();
        controlPanel.revalidate();
    }//GEN-LAST:event_btn_UserAccActionPerformed

    private void btn_userControlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_userControlActionPerformed
        controlPanel.removeAll();
        controlPanel.add(panel_userControl);
        controlPanel.repaint();
        controlPanel.revalidate();
    }//GEN-LAST:event_btn_userControlActionPerformed

    private void btn_ProfitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ProfitActionPerformed
        controlPanel.removeAll();
        controlPanel.add(panel_Profit);
        controlPanel.repaint();
        controlPanel.revalidate();
    }//GEN-LAST:event_btn_ProfitActionPerformed

    private void btn_customerRegActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_customerRegActionPerformed
        controlPanel.removeAll();
        controlPanel.add(panel_customerReg);
        controlPanel.repaint();
        controlPanel.revalidate();
    }//GEN-LAST:event_btn_customerRegActionPerformed

    private void btn_supplierRegActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_supplierRegActionPerformed
        controlPanel.removeAll();
        controlPanel.add(panel_supplierReg);
        controlPanel.repaint();
        controlPanel.revalidate();
    }//GEN-LAST:event_btn_supplierRegActionPerformed

    private void btn_customerLoanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_customerLoanActionPerformed
        controlPanel.removeAll();
        controlPanel.add(panel_customerLoan);
        controlPanel.repaint();
        controlPanel.revalidate();
    }//GEN-LAST:event_btn_customerLoanActionPerformed

    private void rb_userAcc_userActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb_userAcc_userActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rb_userAcc_userActionPerformed

    private void btn_supReg_saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_supReg_saveActionPerformed
        
        SupplierDetailsJpaController supplierControler = new SupplierDetailsJpaController(emfactory);
        SupplierDetails supplier = new SupplierDetails();
        
        supplier.setSupplierName(tf_supReg_supName.getText());
        supplier.setContactName(tf_supReg_contactName.getText());
        supplier.setAddressField1(tf_supReg_address1.getText());
        supplier.setAddressField2(tf_supReg_address2.getText());
        supplier.setAddressField3(tf_supReg_address3.getText());
        supplier.setTelNo(Integer.parseInt(tf_supReg_telNo.getText()));
        supplier.setFaxNo(Integer.parseInt(tf_supReg_faxNo.getText()));
        supplier.setLoan(Integer.parseInt(tf_supReg_loan.getText()));
        supplier.setLoanPeriod(tf_supReg_loanPeriod.getText());
        supplier.setCategory(cb_supReg_category.getSelectedItem().toString());
        
        supplierControler.create(supplier);
        
    }//GEN-LAST:event_btn_supReg_saveActionPerformed

    private void btn_supReg_newCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_supReg_newCustomerActionPerformed
        
        tf_supReg_supName.setText(null);
        tf_supReg_contactName.setText(null);
        tf_supReg_address1.setText(null);
        tf_supReg_address2.setText(null);
        tf_supReg_address3.setText(null);        
        tf_supReg_telNo.setText(null);   
        tf_supReg_faxNo.setText(null);        
        tf_supReg_loan.setText(null);
        tf_supReg_loanPeriod.setText(null);        
                
    }//GEN-LAST:event_btn_supReg_newCustomerActionPerformed

    private void btn_userAcc_saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_userAcc_saveActionPerformed
        
        UserJpaController userController = new UserJpaController(emfactory);
        User user = new User();
        
        user.setName(tf_userAcc_Name.getText());
        user.setPassword(ConvertPasswordToMD5(tf_userAcc_Password.getText()));
        user.setSequrityQ(cb_userAcc_SecurityQ.getSelectedItem().toString());
        user.setSequrityA(tf_userAcc_SecurityA.getText());
        
        userController.create(user);
    }//GEN-LAST:event_btn_userAcc_saveActionPerformed

    
    public String ConvertPasswordToMD5(String Password){
    
        try {
            MessageDigest md = MessageDigest.getInstance("MD5");
            md.update(Password.getBytes());
            
            byte byteData[] = md.digest();
             //convert the byte to hex format method 1
            StringBuffer sb = new StringBuffer();
            
            for (int i = 0; i < byteData.length; i++) {
                sb.append(Integer.toString((byteData[i] & 0xff) + 0x100, 16).substring(1));
            }
            
            return sb.toString();
        } catch (NoSuchAlgorithmException ex) {
            Logger.getLogger(MainMenu.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        return null;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
                
                MainMenu mainLayout = new MainMenu();
                mainLayout.setExtendedState(JFrame.MAXIMIZED_BOTH);
                mainLayout.setSize(screenSize);
                mainLayout.setVisible(true);
                mainLayout.setResizable(false);
                mainLayout.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                
                //new MainMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Profit;
    private javax.swing.JButton btn_UserAcc;
    private javax.swing.JButton btn_customReg_newCustomer;
    private javax.swing.JButton btn_customReg_save;
    private javax.swing.JButton btn_customerLoan;
    private javax.swing.JButton btn_customerReg;
    private javax.swing.JButton btn_supReg_newCustomer;
    private javax.swing.JButton btn_supReg_save;
    private javax.swing.JButton btn_supplierReg;
    private javax.swing.JButton btn_userAcc_newUser;
    private javax.swing.JButton btn_userAcc_save;
    private javax.swing.JButton btn_userControl;
    private javax.swing.JComboBox cb_supReg_category;
    private javax.swing.JComboBox cb_userAcc_SecurityQ;
    private javax.swing.JPanel controlLeftPanel;
    private javax.swing.JPanel controlPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTabbedPane jTabbedPane7;
    private javax.swing.JPanel panel_Profit;
    private javax.swing.JPanel panel_UserAcc;
    private javax.swing.JPanel panel_customerLoan;
    private javax.swing.JPanel panel_customerReg;
    private javax.swing.JPanel panel_supplierReg;
    private javax.swing.JPanel panel_userControl;
    private javax.swing.JRadioButton rb_customReg_active;
    private javax.swing.JRadioButton rb_customReg_deactive;
    private javax.swing.JRadioButton rb_userAcc_Admin;
    private javax.swing.JRadioButton rb_userAcc_user;
    private javax.swing.JPanel tabAction;
    private javax.swing.JPanel tabControl;
    private javax.swing.JPanel tabItem;
    private javax.swing.JPanel tabReport;
    private javax.swing.JPanel tabTransaction;
    private javax.swing.JTextField tf_customReg_Address1;
    private javax.swing.JTextField tf_customReg_Address2;
    private javax.swing.JTextField tf_customReg_Address3;
    private javax.swing.JTextField tf_customReg_Tel;
    private javax.swing.JTextField tf_customReg_loan;
    private javax.swing.JTextField tf_customReg_loanPeriod;
    private javax.swing.JTextField tf_customReg_name;
    private javax.swing.JTextField tf_supReg_address1;
    private javax.swing.JTextField tf_supReg_address2;
    private javax.swing.JTextField tf_supReg_address3;
    private javax.swing.JTextField tf_supReg_contactName;
    private javax.swing.JTextField tf_supReg_faxNo;
    private javax.swing.JTextField tf_supReg_loan;
    private javax.swing.JTextField tf_supReg_loanPeriod;
    private javax.swing.JTextField tf_supReg_supName;
    private javax.swing.JTextField tf_supReg_telNo;
    private javax.swing.JTextField tf_userAcc_Name;
    private javax.swing.JPasswordField tf_userAcc_Password;
    private javax.swing.JTextField tf_userAcc_SecurityA;
    private javax.swing.JPasswordField tf_userAcc_confirmPass;
    // End of variables declaration//GEN-END:variables
}
